
[general]
music_volume = 0.05
cache_dir = 'song_cache'

[discord]
token = "..."
add_bot_url = "https://discordapp.com/oauth2/authorize?client_id={CLIENT_ID}&scope=bot&permissions=3148800"

[gmusic]
username = "me@gmail.com"
password = "apppassword"

[windows]
opus_dll = "libopus-0.x64.dll"

[debug]
use_reloader = true
