
[general]
music_volume = 0.05
debug = false
#use_reloader = true

[discord]
token = "..."
add_bot_url = "https://discordapp.com/oauth2/authorize?client_id={CLIENT_ID}&scope=bot&permissions=3148800"

[gmusic]
username = "me@gmail.com"
password = "apppassword"
